export const products = [
  {
    id: 1,
    name: 'Giày thể thao 1',
    price: 150,
    oldPrice: 210,
    image: '/img/product/p1.jpg',
  },
  {
    id: 2,
    name: 'Giày thể thao 2',
    price: 150,
    oldPrice: 210,
    image: '/img/product/p2.jpg',
  },
  {
    id: 3,
    name: 'Giày thể thao 3',
    price: 150,
    oldPrice: 210,
    image: '/img/product/p3.jpg',
  },
  {
    id: 4,
    name: 'Giày thể thao 4',
    price: 150,
    oldPrice: 210,
    image: '/img/product/p4.jpg',
  },
  {
    id: 5,
    name: 'Giày thể thao 5',
    price: 150,
    oldPrice: 210,
    image: '/img/product/p5.jpg',
  },
  {
    id: 6,
    name: 'Giày thể thao 6',
    price: 150,
    oldPrice: 210,
    image: '/img/product/p6.jpg',
  },
  {
    id: 7,
    name: 'Giày thể thao 7',
    price: 150,
    oldPrice: 210,
    image: '/img/product/p7.jpg',
  },
  {
    id: 8,
    name: 'Giày thể thao 8',
    price: 150,
    oldPrice: 210,
    image: '/img/product/p8.jpg',
  },
  {
    id: 9,
    name: 'Giày thể thao 9',
    price: 150,
    oldPrice: 210,
    image: '/img/product/p1.jpg',
  },
  {
    id: 10,
    name: 'Giày thể thao 10',
    price: 150,
    oldPrice: 210,
    image: '/img/product/p2.jpg',
  },
]
